services:
  - type: web
    name: crypto-signals
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crypto_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 